### ISSUE TITLE
[Bug] Section switching reverts selected week to current week in Fall 2021 scheduler

### ISSUE THREAD

**Issue by jensengillett** [VikeLabs/courseup#173]
In the 'Fall 2021' view, when you change which lecture/lab/tutorial section you have selected for a class, the date you have selected in the scheduler returns to the present week (May 31st) instead of staying at the week you were looking at before. 
I tested it on both the dev and prod sites (by accident, didn't realize there were two until someone mentioned it), and it's present in both.

Video - https://youtu.be/woT5HrA8zMs

This is slightly annoying because it means to see how your changes affected other classes, you have to mash the 'next week' button a bunch of times after switching a section. Minor inconvenience at best, but probably an easy fix.

The same behaviour is observable in the Winter 2022 term, though in that case it resets back to the week of January 10-14, which is much more tolerable since that's where the courses start instead of 3 months prior. 

Bonus points if you make it so it remembers the week you had selected when switching your section. I wouldn't say that's a _necessary_ change (that's more a feature suggestion from me), but it's a little more user-friendly IMO.

**Comment by zthh626** [comment]
I think this is due to the mashing of logic of going to the first event + a week to see all courses and logic of finding the first week in a term when no events.. The fix is probably to move the date prop and selector onClicks out of the calendar component and into SchedulerContainer so that we can observe more states. I'll try and have a fix out by the end of the weekend. Hopefully with this change it'll work way more as expected!

**Comment by keithradford** [comment]
@jensengillett The problem with the fall semester going to the wrong date has now been addressed. Additionally, the "default date" it jumps back to is a couple days ahead of what it was before, so when you change sections it should jump back to a spot where most if not all sections are visible (this is assuming it's a regularly scheduled event & labs start in the 2nd week of classes).

We have plans to try and address it so the selected week persists when changing sections, but for now I'll close this issue since the major bug has been fixed.
