### ISSUE TITLE
Bug: Weekly View Reset After Course Update

### ISSUE THREAD

**Issue by FlyteWizard** [VikeLabs/courseup#413]
**Describe the Bug/Issue**

When updating a course on the scheduler *after* changing the weekly view resets the weekly view to the current week.

**To Reproduce**

1. Go to https://courseup.vikelabs.ca/scheduler/202209
2. Add courses to schedule
3. Change the weekly view to a different week
4. Notice the reset of the weekly view to the current week.

**Expected Behaviour**

I expect the weekly view to not reset when updating courses.

**Screenshots**

https://user-images.githubusercontent.com/10472448/188323673-761b3707-a168-4caa-9432-142d710da4e2.mov

**Desktop/Mobile**

- OS: macOS
- Browser: Safari
- Version: Latest

**Additional Context**

Apologies if this has already been report, please close if duplicate.

**Comment by keithradford** [comment]
Ah, I know why this was happening.

CourseUp says it's the fall semester after September 1st. If you're browsing a schedule that is for the current semester, the behaviour is to reset back to the week you're in. This usually won't show any visual change as most weeks are the same once you're in the midst of the semester, but since it was early in the month it was resetting you to an early state that didn't show the whole timetable.
